name: Deploy to GitHub Pages from RepoA's Build Artifacts

on:
  workflow_run:
    workflows: ["Build and Deploy to Another Repository"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository B (Target Repo)
      uses: actions/checkout@v4
      with:
        repository: DhruviHiteshkumarSuthar/devops-fusion-ui-dist  # Target repo
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Download Build Artifacts from RepoA
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: ./  # Download to the root of the target repo

    - name: Set Git Identity
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

    - name: Checkout gh-pages Branch
      run: |
        git fetch origin
        git checkout gh-pages

    - name: Clean Target Directory
      run: |
        rm -rf *  # Clean the current files in the target repo

    - name: Move Build Files to Root
      run: |
        mv browser/* .  # Move contents from 'browser' folder to the root
        rm -rf browser  # Remove the empty 'browser' folder

    - name: Disable Jekyll for GitHub Pages
      run: echo > .nojekyll

    - name: Commit and Push to Repository B
      run: |
        git add --all
        git commit -m "Deploy new build" || echo "No changes to commit"
        git push origin gh-pages --force
